paths:
  images: ..\Retroarch Bubble Images
  vita:
    cores: app0:{core}_libretro.self
    roms: ux0:ROMS/{system}/{filename}
systems:
  GBA:
    name: Gameboy Advance
    core: vba_next
    format: "{title}.gba"
  NES:
    name: Nintendo Entertainment System
    core: quicknes
    format: "{title}.nes"